site_name: Lottie Docs
site_description: Documentation for the Lottie animation format
copyright: Copyright (C) 2021-2022
extra:
    lottie_player_version: 5.12.2
theme:
    name: cinder
    custom_dir: theme
    highlightjs: false
repo_url: https://github.com/LottieFiles/lottie-docs
edit_uri: https://github.com/LottieFiles/lottie-docs/edit/main/docs
use_directory_urls: true
site_url: https://lottiefiles.github.io/lottie-docs/
markdown_extensions:
    - md_in_html
    - md_extensions
    - footnotes
extra_css:
    - /lottie-docs/style/style.css
    - /lottie-docs/style/lottie-theme.css
plugins:
    - search
    - redirects:
        redirect_maps:
            "playground/explain.md": "playground/json_editor.md"

nav:
    - "Home" : index.md
    - "Guide":
        - "Introduction" : Introduction.md
        - breakdown/bouncy_ball.md
        - breakdown/lottie_from_scratch.md
        - breakdown/bezier.md
        - breakdown/precomps.md
    - "Lottie Format":
        - concepts.md
        - animation.md
        - layers.md
        - "Shapes": shapes.md
        - assets.md
        - effects.md
        - constants.md
        - text.md
        - expressions.md
        - compat.md
    - "Playground":
        - "Builder": playground/builder.md
        - "JSON Editor": playground/json_editor.md
    - "Advanced Concept":
        - rendering.md
        - schema.md
        - advanced_interactions.md
        - aep.md
