name: Build Pages
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup
        run: |
            sudo apt update -q
            sudo apt install -yy python3 python3-pip python3-virtualenv make
            make install_dependencies
      -
        name: Docs
        run: |
            make docs
      -
        name: Validate
        run: |
            make validate
            make validate_links
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
