name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup
        run: |
            sudo apt update -q
            sudo apt install -yy python python3-pip python3-virtualenv make
            make install_dependencies
      -
        name: Docs
        run: |
            make docs
      -
        name: Validate
        run: |
            make validate
            make validate_links
